language: ruby
rvm:
  - 2.5.1

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html --alt-ignore '/.*/'

# branch whitelist - this seems like a no-op (since the RegEx includes
# everything), but it isn't: by default, Travis excludes the `gh-pages` branch,
# and you need to explicitly enable it.
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /(.*)/       # test every other branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
