url: https://moveit.ros.org
name: MoveIt Motion Planning Framework
description: Incorporating the latest advances in motion planning, manipulation, 3D perception, kinematics, control and navigation.

plugins:
  - jekyll-feed
  - jekyll-redirect-from

sass:
  style: compressed

#RSS Config
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
